/**
 * geoUtils.mercator-conformance.test.ts
 *
 * This project has two pieces of coordinate math that were, for a while,
 * described as competing "georeference models" that would eventually need
 * to be unified: the general control-point calibration solver in
 * `geoUtils.ts` (fits a 4-DOF anti-similarity or 6-DOF least-squares affine
 * transform from operator-placed control points on an arbitrary venue
 * image), and `dev/crowdcad-tak-bridge/georef.js` (the exact analytic
 * inverse of a known, north-up Web Mercator tile crop produced by
 * `make-campus-map.py`, with no rotation or shear terms at all).
 *
 * That framing was wrong. `georef.js`'s transform is a DEGENERATE special
 * case of the affine family: diagonal-only (no cross terms), because a
 * north-up Mercator crop has no rotation or shear to represent. This test
 * proves that numerically — it fits `geoUtils.ts`'s affine solver to the
 * four corners of a real `make-campus-map.py` output (using `georef.js`'s
 * own `unproject()` as the source of truth for what those corners' lat/lon
 * are), and shows the two agree to a few centimetres everywhere they
 * overlap. They are not rivals. `geoUtils.ts` is the general model that
 * applies to every real venue map — including ones that are not north-up,
 * which `georef.js` cannot represent at all — and `georef.js` is an exact
 * shortcut valid only for its own narrow input shape.
 *
 * All reference values here are pinned literals, not computed by importing
 * `georef.js` at test time: the `core/` submodule cannot import from the
 * root-level `dev/` directory (submodule boundary; CI runs `core` alone).
 * They were generated by running `node` against `georef.js` directly,
 * against the real sidecar at `dev/crowdcad-tak-bridge/campus-map.json`,
 * e.g.:
 *
 *   const { Georeference } = require('./georef');
 *   const geo = new Georeference(require('./campus-map.json'));
 *   geo.unproject(50, 50); // => { lat: 37.87200033254645, lon: -122.258 }
 *
 * If `make-campus-map.py`'s bbox (or zoom) ever changes, `campus-map.json`
 * gets regenerated, and every pinned literal below is stale — regenerate
 * them the same way. `dev/crowdcad-tak-bridge/georef.test.js` carries a
 * tripwire test that pins the same four corner values so a bridge-side
 * bbox change can't silently invalidate this file without a visible
 * failure over there too.
 */

import { describe, expect, it } from 'vitest';

import type { ControlPoint, Georeference } from '@/app/types';
import { METRES_PER_DEGREE_LATITUDE, pixelToLatLon, solveGeoreference } from '@/lib/geoUtils';

function makeGeoref(controlPoints: ControlPoint[]): Georeference {
  return {
    controlPoints,
    version: 1,
    updatedAt: 0,
  };
}

// ---------------------------------------------------------------------------
// Fixture, pinned from dev/crowdcad-tak-bridge/campus-map.json. This MUST
// match that sidecar's `mercator` block and image dimensions exactly. If
// make-campus-map.py's bbox or zoom changes, campus-map.json is
// regenerated and every literal in this file — this block, the corner
// control points below, and the interior/perturbed reference values —
// must be regenerated too (see the file header for how).
// ---------------------------------------------------------------------------
const CAMPUS_MAP_MERCATOR = {
  x_left: 21019.579733333332,
  x_right: 21026.86151111111,
  y_top: 50614.08732637552,
  y_bottom: 50620.54456805397,
  tile_size: 256,
  n: 131072,
} as const;
const CAMPUS_MAP_WIDTH = 1865;
const CAMPUS_MAP_HEIGHT = 1653;

// The four image corners, paired with the exact lat/lon georef.js's
// unproject() computes for them against the mercator block above. These
// equal the sidecar's bbox corners (south 37.865 / west -122.268 / north
// 37.879 / east -122.248) because make-campus-map.py crops tile space so
// the image edges land exactly on the bbox — the trailing-digit noise on
// two of them (37.86500000000001 instead of 37.865) is ordinary
// floating-point residue from the tile-space round trip, not a real
// discrepancy (it's ~1.6 nanometres of latitude).
const CORNER_CONTROL_POINTS: ControlPoint[] = [
  { x: 0, y: 0, lat: 37.879, lon: -122.268, label: 'NW' },
  { x: 100, y: 0, lat: 37.879, lon: -122.248, label: 'NE' },
  { x: 0, y: 100, lat: 37.86500000000001, lon: -122.268, label: 'SW' },
  { x: 100, y: 100, lat: 37.86500000000001, lon: -122.248, label: 'SE' },
];

// Interior (non-corner) points: exact Mercator-inverse lat/lon from
// georef.js's unproject(), at image percentages that are NOT control
// points. This is what the affine fit (built only from the four corners
// above) is compared against, to prove interior agreement rather than just
// corner agreement.
const MERCATOR_EXACT_INTERIOR = {
  center: { x: 50, y: 50, lat: 37.87200033254645, lon: -122.258 },
  quarter: { x: 25, y: 75, lat: 37.868500249407255, lon: -122.263 },
  nearCorner: { x: 10, y: 90, lat: 37.86640011971474, lon: -122.26599999999999 },
  nearEdge: { x: 95, y: 5, lat: 37.87830006318501, lon: -122.249 },
};

/**
 * Distance in metres between two lat/lon points, measured the same way
 * georeferenceResiduals() in geoUtils.ts does: project both into the local
 * tangent-plane (u, v) frame using the solved transform's own
 * lat0/lon0/cosLat0, take the Euclidean distance in degree-equivalent
 * units, then scale by METRES_PER_DEGREE_LATITUDE. Reuses cosLat0 from the
 * transform rather than inventing a second distance model.
 */
function metresBetween(
  latA: number,
  lonA: number,
  latB: number,
  lonB: number,
  cosLat0: number
): number {
  const du = (lonA - lonB) * cosLat0;
  const dv = latA - latB;
  return Math.sqrt(du * du + dv * dv) * METRES_PER_DEGREE_LATITUDE;
}

describe('geoUtils affine solver vs. georef.js Mercator-exact crop (conformance)', () => {
  const georef = makeGeoref(CORNER_CONTROL_POINTS);
  const transform = solveGeoreference(georef);

  it('solves a valid transform from the four corner control points', () => {
    expect(transform).not.toBeNull();
  });

  it('fixture matches the documented campus-map.json sidecar shape', () => {
    // Sanity check on the pinned fixture constants themselves, so a future
    // edit that accidentally changes one of these without updating the
    // header comment / regenerating the rest of the file fails loudly.
    expect(CAMPUS_MAP_WIDTH).toBe(1865);
    expect(CAMPUS_MAP_HEIGHT).toBe(1653);
    expect(CAMPUS_MAP_MERCATOR.tile_size).toBe(256);
    expect(CAMPUS_MAP_MERCATOR.n).toBe(2 ** 17); // zoom 17
    expect(CAMPUS_MAP_MERCATOR.x_right).toBeGreaterThan(CAMPUS_MAP_MERCATOR.x_left);
    expect(CAMPUS_MAP_MERCATOR.y_bottom).toBeGreaterThan(CAMPUS_MAP_MERCATOR.y_top);
  });

  describe('corner exactness', () => {
    // Mirrors the "hits control points exactly" assertion style in
    // geoUtils.test.ts: pixelToLatLon at each control point reproduces
    // that point's lat/lon to within ~1cm (toBeCloseTo(..., 9) on raw
    // degrees is ~1.1e-4 m of latitude, comfortably tighter than 1cm).
    for (const cp of CORNER_CONTROL_POINTS) {
      it(`reproduces corner (${cp.x}, ${cp.y}) [${cp.label}]`, () => {
        expect(transform).not.toBeNull();
        if (!transform) return;

        const { lat, lon } = pixelToLatLon(transform, cp.x, cp.y);
        expect(lat).toBeCloseTo(cp.lat, 9);
        expect(lon).toBeCloseTo(cp.lon, 9);
      });
    }
  });

  describe('interior agreement (the point of this test)', () => {
    // At several non-corner points, the affine transform fitted ONLY from
    // the four corners agrees with the independently-computed
    // Mercator-exact lat/lon to within 10cm. This is the numeric proof
    // that the affine solver and the Mercator crop are the same math over
    // their overlap: georef.js's exact analytic transform is a
    // rotation-free, shear-free special case that the general affine
    // solver can represent to sub-decimetre precision at venue scale.
    const TOLERANCE_METRES = 0.1;

    for (const [label, point] of Object.entries(MERCATOR_EXACT_INTERIOR)) {
      it(`agrees with the Mercator-exact value at ${label} (${point.x}, ${point.y}) to within ${TOLERANCE_METRES} m`, () => {
        expect(transform).not.toBeNull();
        if (!transform) return;

        const affine = pixelToLatLon(transform, point.x, point.y);
        const distanceMetres = metresBetween(
          affine.lat,
          affine.lon,
          point.lat,
          point.lon,
          transform.cosLat0
        );

        // Real measured divergence at venue scale (UC Berkeley campus bbox,
        // zoom 17) as of when this fixture was generated:
        //   center (50,50):     ~0.037 m
        //   quarter (25,75):    ~0.028 m
        //   nearCorner (10,90): ~0.013 m
        //   nearEdge (95,5):    ~0.007 m
        // All comfortably inside the 10cm bound below.
        expect(distanceMetres).toBeLessThan(TOLERANCE_METRES);
      });
    }
  });

  describe('calibration-error sensitivity (the real accuracy risk)', () => {
    // Perturb the four corner control points by small, hand-written FIXED
    // offsets (no Math.random() — this suite is deterministic) simulating
    // an operator who typed slightly-off lat/lon values while calibrating
    // a venue map. Refit the affine transform from the perturbed points
    // and check how far the result diverges from the true Mercator-exact
    // lat/lon at the same interior points used above.
    //
    // The point of this case: the divergence here (metres) is one to two
    // orders of magnitude LARGER than the sub-decimetre disagreement
    // between the affine solver and georef.js measured above with correct
    // control points. That gap is the whole story — the real accuracy
    // risk in this system is operator calibration precision, NOT any
    // disagreement between the two pieces of math. A perfect model fed
    // slightly-wrong inputs still produces a slightly-wrong answer.
    //
    // Offsets are deliberately asymmetric (not a mirrored +/- pattern)
    // because a symmetric perturbation pattern cancels out exactly at the
    // image center under a least-squares affine fit — that would hide the
    // effect this test exists to demonstrate.
    const PERTURBED_CONTROL_POINTS: ControlPoint[] = [
      { x: 0, y: 0, lat: 37.879 + 0.00005, lon: -122.268 - 0.00004, label: 'NW (perturbed)' },
      { x: 100, y: 0, lat: 37.879 + 0.00003, lon: -122.248 + 0.00006, label: 'NE (perturbed)' },
      {
        x: 0,
        y: 100,
        lat: 37.86500000000001 - 0.00002,
        lon: -122.268 + 0.00003,
        label: 'SW (perturbed)',
      },
      {
        x: 100,
        y: 100,
        lat: 37.86500000000001 + 0.00004,
        lon: -122.248 - 0.00002,
        label: 'SE (perturbed)',
      },
    ];
    const perturbedGeoref = makeGeoref(PERTURBED_CONTROL_POINTS);
    const perturbedTransform = solveGeoreference(perturbedGeoref);

    // Bounds are loose on purpose: this isn't pinning the perturbed fit's
    // exact output (that would just be re-deriving the affine algebra),
    // it's documenting that miscalibration error is BOUNDED (a few tens of
    // centimetres to a few metres for offsets of this size, not
    // catastrophic) and NON-TRIVIAL (far above the sub-decimetre
    // model-agreement noise floor established above).
    const NON_TRIVIAL_METRES = 0.3;
    const BOUNDED_METRES = 10;

    for (const [label, point] of Object.entries(MERCATOR_EXACT_INTERIOR)) {
      it(`diverges from the Mercator-exact value at ${label} by a bounded, non-trivial amount once control points are miscalibrated`, () => {
        expect(perturbedTransform).not.toBeNull();
        if (!perturbedTransform) return;

        const perturbedResult = pixelToLatLon(perturbedTransform, point.x, point.y);
        const distanceMetres = metresBetween(
          perturbedResult.lat,
          perturbedResult.lon,
          point.lat,
          point.lon,
          perturbedTransform.cosLat0
        );

        // Real measured divergence with this perturbation:
        //   center (50,50):     ~2.82 m
        //   quarter (25,75):    ~1.36 m
        //   nearCorner (10,90): ~0.67 m
        //   nearEdge (95,5):    ~5.59 m
        expect(distanceMetres).toBeGreaterThan(NON_TRIVIAL_METRES);
        expect(distanceMetres).toBeLessThan(BOUNDED_METRES);
      });
    }
  });
});
